INSERT INTO ACTOR (FIRST_NAME, LAST_NAME, PASSWORD, EMAIL, BALANCE, ROLE) VALUES ('Teszt','Elek', '$2a$10$lW9Q6thFdccwPiRyOmQmreEtNhERoYGEsYKRL3uV97Q9u2ZGKxusW', 'teszt@proba.hu', 39000, 'ROLE_USER');
INSERT INTO ACTOR (FIRST_NAME, LAST_NAME, PASSWORD, EMAIL, BALANCE, ROLE) VALUES ('Másik','Felhasználó', '$2a$10$lW9Q6thFdccwPiRyOmQmreEtNhERoYGEsYKRL3uV97Q9u2ZGKxusW', 'masik@proba.hu', 65000, 'ROLE_USER');
INSERT INTO ACTOR (FIRST_NAME, LAST_NAME, PASSWORD, EMAIL, BALANCE, ROLE) VALUES ('Admin','Admin', '$2a$10$lW9Q6thFdccwPiRyOmQmreEtNhERoYGEsYKRL3uV97Q9u2ZGKxusW', 'admin@admin.hu', 0, 'ROLE_ADMIN');


INSERT INTO PARTNER (NAME, CITY, ADDRESS, TAX_NUM) VALUES ('Börgödör', 'Érd', 'Vasút utca 12.', '12345678910');
INSERT INTO PARTNER (NAME, CITY, ADDRESS, TAX_NUM) VALUES ('Tesco', 'Érd', 'Budai út 1', '12345678999');
INSERT INTO PARTNER (NAME, CITY, ADDRESS, TAX_NUM) VALUES ('Benzinkút', 'Budapest', 'Kinizsi utca 1', '12345678333');
INSERT INTO PARTNER (NAME, CITY, ADDRESS, TAX_NUM) VALUES ('Munkahely', 'Budapest', 'Alma utca 1', '12345678333');
INSERT INTO PARTNER (NAME, CITY, ADDRESS, TAX_NUM) VALUES ('BKV', 'Budapest', 'Váci út 1', '12345678333');
INSERT INTO PARTNER (NAME, CITY, ADDRESS, TAX_NUM) VALUES ('Ételfutár', 'Budapest', 'Nyugati téri aluljáró', '12345678333');

INSERT INTO ITEM (ACTOR_ID, PARTNER_ID, AMOUNT, DATE_OF_DEADLINE, DATE_OF_COMPLETION, DESCRIPTION) VALUES (1,1, -1000,  '2018-11-10', '2018-11-10', 'Sok sör kell még');
INSERT INTO ITEM (ACTOR_ID, PARTNER_ID, AMOUNT, DATE_OF_DEADLINE, DATE_OF_COMPLETION, DESCRIPTION) VALUES (1,2, -2000,  '2018-11-03', '2018-11-03', 'Gyros, csípõssel');
INSERT INTO ITEM (ACTOR_ID, PARTNER_ID, AMOUNT, DATE_OF_DEADLINE, DATE_OF_COMPLETION, DESCRIPTION) VALUES (1,2, -3000,  '2018-11-09', '2018-11-08', 'Alkohol');
INSERT INTO ITEM (ACTOR_ID, PARTNER_ID, AMOUNT, DATE_OF_DEADLINE, DATE_OF_COMPLETION, DESCRIPTION) VALUES (1,3, -10000, '2018-11-12', '2018-11-13', 'Benzin');
INSERT INTO ITEM (ACTOR_ID, PARTNER_ID, AMOUNT, DATE_OF_DEADLINE, DATE_OF_COMPLETION, DESCRIPTION) VALUES (1,4, 55000, '2018-11-05', '2018-11-05', 'Fizetés');
INSERT INTO ITEM (ACTOR_ID, PARTNER_ID, AMOUNT, DATE_OF_DEADLINE, DATE_OF_COMPLETION, DESCRIPTION) VALUES (2,4, 100000, '2018-11-06', '2018-11-06', 'Fizetés');
INSERT INTO ITEM (ACTOR_ID, PARTNER_ID, AMOUNT, DATE_OF_DEADLINE, DATE_OF_COMPLETION, DESCRIPTION) VALUES (2,5, -10000,  '2018-11-07', '2018-11-07', 'Bérlet');
INSERT INTO ITEM (ACTOR_ID, PARTNER_ID, AMOUNT, DATE_OF_DEADLINE, DATE_OF_COMPLETION, DESCRIPTION) VALUES (2,6, -10000,  '2018-11-05', '2018-11-03', 'Heti ebédrendelés');
INSERT INTO ITEM (ACTOR_ID, PARTNER_ID, AMOUNT, DATE_OF_DEADLINE, DATE_OF_COMPLETION, DESCRIPTION) VALUES (2,2, -8000,  '2018-11-09', '2018-11-08', 'Ruha');
INSERT INTO ITEM (ACTOR_ID, PARTNER_ID, AMOUNT, DATE_OF_DEADLINE, DATE_OF_COMPLETION, DESCRIPTION) VALUES (2,2, -2000,  '2018-11-09', '2018-11-09', 'Telefon');
INSERT INTO ITEM (ACTOR_ID, PARTNER_ID, AMOUNT, DATE_OF_DEADLINE, DATE_OF_COMPLETION, DESCRIPTION) VALUES (2,6, -5000, '2018-11-12', '2018-11-10', 'Heti ebédrendelés');

INSERT INTO CATEGORY (name) VALUES ('Tankolás');
INSERT INTO CATEGORY (name) VALUES ('Bevásárlás');
INSERT INTO CATEGORY (name) VALUES ('Kocsmázás');
INSERT INTO CATEGORY (name) VALUES ('Munkabér');
INSERT INTO CATEGORY (name) VALUES ('Étel');

INSERT INTO ITEM_CATEGORIES (ITEMS_ID, CATEGORIES_ID) VALUES (1, 3);
INSERT INTO ITEM_CATEGORIES (ITEMS_ID, CATEGORIES_ID) VALUES (2, 2);
INSERT INTO ITEM_CATEGORIES (ITEMS_ID, CATEGORIES_ID) VALUES (2, 5);
INSERT INTO ITEM_CATEGORIES (ITEMS_ID, CATEGORIES_ID) VALUES (2, 2);
INSERT INTO ITEM_CATEGORIES (ITEMS_ID, CATEGORIES_ID) VALUES (3, 3);
INSERT INTO ITEM_CATEGORIES (ITEMS_ID, CATEGORIES_ID) VALUES (5, 4);
INSERT INTO ITEM_CATEGORIES (ITEMS_ID, CATEGORIES_ID) VALUES (6, 4);
INSERT INTO ITEM_CATEGORIES (ITEMS_ID, CATEGORIES_ID) VALUES (8, 5);
INSERT INTO ITEM_CATEGORIES (ITEMS_ID, CATEGORIES_ID) VALUES (11, 5);