INSERT INTO ACTOR (FIRST_NAME, LAST_NAME, PASSWORD, EMAIL, BALANCE, ROLE) VALUES ('Teszt','Elek', '$2a$10$lW9Q6thFdccwPiRyOmQmreEtNhERoYGEsYKRL3uV97Q9u2ZGKxusW', 'teszt@proba.hu', 5000, 'ROLE_USER');

INSERT INTO PARTNER (NAME, CITY, ADDRESS, TAX_NUM) VALUES ('Börgödör', 'Érd', 'Vasút utca 12.', '12345678910');
INSERT INTO PARTNER (NAME, CITY, ADDRESS, TAX_NUM) VALUES ('Tesco', 'Érd', 'Budai út 1', '12345678999');
INSERT INTO PARTNER (NAME, CITY, ADDRESS, TAX_NUM) VALUES ('Benzinkút', 'Budapest', 'Kinizsi utca 1', '12345678333');

INSERT INTO ITEM (ACTOR_ID, PARTNER_ID, AMOUNT, DATE_OF_DEADLINE, DATE_OF_COMPLETION, DESCRIPTION) VALUES (1,1, 3000,  '2018-11-10', '2018-11-10', 'Sok sör kell még');
INSERT INTO ITEM (ACTOR_ID, PARTNER_ID, AMOUNT, DATE_OF_DEADLINE, DATE_OF_COMPLETION, DESCRIPTION) VALUES (1,2, 1520,  '2018-11-03', '2018-11-03', 'Gyros, csípőssel');
INSERT INTO ITEM (ACTOR_ID, PARTNER_ID, AMOUNT, DATE_OF_DEADLINE, DATE_OF_COMPLETION, DESCRIPTION) VALUES (1,2, 9000,  '2018-11-09', '2018-11-08', 'Alkohol');
INSERT INTO ITEM (ACTOR_ID, PARTNER_ID, AMOUNT, DATE_OF_DEADLINE, DATE_OF_COMPLETION, DESCRIPTION) VALUES (1,3, 12300, '2018-11-12', '2018-11-13', 'Benzin');

INSERT INTO CATEGORY (name) VALUES ('Tankolás');
INSERT INTO CATEGORY (name) VALUES ('Bevásárlás');
INSERT INTO CATEGORY (name) VALUES ('Kocsmázás');

INSERT INTO ITEM_CATEGORIES (ITEMS_ID, CATEGORIES_ID) VALUES (1, 3);
INSERT INTO ITEM_CATEGORIES (ITEMS_ID, CATEGORIES_ID) VALUES (2, 2);
INSERT INTO ITEM_CATEGORIES (ITEMS_ID, CATEGORIES_ID) VALUES (2, 3);
INSERT INTO ITEM_CATEGORIES (ITEMS_ID, CATEGORIES_ID) VALUES (2, 2);
INSERT INTO ITEM_CATEGORIES (ITEMS_ID, CATEGORIES_ID) VALUES (3, 3);